-- Criação da tabela Clientes.
CREATE TABLE "SYSTEM"."TB_CLIENTES" (
    "NR_CPF"             VARCHAR2(11 BYTE),
    "NM_NOME_CLIENTE"    VARCHAR2(150 BYTE),
    "NR_CEP"             VARCHAR2(8 BYTE),
    "NM_LOGRADOURO"      VARCHAR2(300 BYTE),
    "NR_NUMERO"          NUMBER(5, 0),
    "NM_COMPLEMENTO"     VARCHAR2(300 BYTE),
    "NM_BAIRRO"          VARCHAR2(150 BYTE),
    "NM_CIDADE"          VARCHAR2(150 BYTE),
    "NM_ESTADO"          VARCHAR2(2 BYTE),
    "DT_NASCIMENTO"      DATE,
    "NR_IDADE"           NUMBER(*, 0),
    "NM_SEXO"            VARCHAR2(1 BYTE),
    "NR_LIMETE_CREDITO"  NUMBER(15, 2),
    "NR_VOLUME_COMPRA"   NUMBER,
    "NR_PRIMEIRA_COMPRA" NUMBER(1, 0)
);

-- Criação da tabela Produtos.
CREATE TABLE "SYSTEM"."TB_PRODUTOS" (
    "CD_PRODUTO"     VARCHAR2(20 BYTE),
    "NM_PRODUTO"     VARCHAR2(150 BYTE),
    "NM_EMBALAGEM"   VARCHAR2(50 BYTE),
    "NM_TAMANHO"     VARCHAR2(50 BYTE),
    "NM_SABOR"       VARCHAR2(50 BYTE),
    "NR_PRECO_LISTA" NUMBER
);

-- Criação da tabela Vendedores.
CREATE TABLE "SYSTEM"."TB_VENDEDORES" (
    "NR_MATRICULA_VENDEDOR"  NVARCHAR2(5),
    "NM_VENDEDOR"            NVARCHAR2(100),
    "DT_ADMISSAO_VENDEDOR"   DATE,
    "NR_PERCENTUAL_COMISSAO" NUMBER
);